// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
void ui_event_Button21(lv_event_t * e);
extern lv_obj_t * ui_Button21;
void ui_event_Button41(lv_event_t * e);
extern lv_obj_t * ui_Button41;
void ui_event_Button81(lv_event_t * e);
extern lv_obj_t * ui_Button81;
void ui_event_Button51(lv_event_t * e);
extern lv_obj_t * ui_Button51;
void ui_event_Button11(lv_event_t * e);
extern lv_obj_t * ui_Button11;
void ui_event_Button31(lv_event_t * e);
extern lv_obj_t * ui_Button31;
void ui_event_Button61(lv_event_t * e);
extern lv_obj_t * ui_Button61;
void ui_event_Button01(lv_event_t * e);
extern lv_obj_t * ui_Button01;
void ui_event_Button71(lv_event_t * e);
extern lv_obj_t * ui_Button71;
void ui_event_Button91(lv_event_t * e);
extern lv_obj_t * ui_Button91;
void ui_event_ButtonX(lv_event_t * e);
extern lv_obj_t * ui_ButtonX;
void ui_event_ButtonCF(lv_event_t * e);
extern lv_obj_t * ui_ButtonCF;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_TextAreaS1;
// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
extern lv_obj_t * ui_Screen2;
void ui_event_Button12(lv_event_t * e);
extern lv_obj_t * ui_Button12;
void ui_event_Button22(lv_event_t * e);
extern lv_obj_t * ui_Button22;
void ui_event_Button32(lv_event_t * e);
extern lv_obj_t * ui_Button32;
void ui_event_Button42(lv_event_t * e);
extern lv_obj_t * ui_Button42;
void ui_event_Button52(lv_event_t * e);
extern lv_obj_t * ui_Button52;
extern lv_obj_t * ui_Image3;
// SCREEN: ui_Screen3
void ui_Screen3_screen_init(void);
extern lv_obj_t * ui_Screen3;
void ui_event_Button2(lv_event_t * e);
extern lv_obj_t * ui_Button2;
void ui_event_Button13(lv_event_t * e);
extern lv_obj_t * ui_Button13;
extern lv_obj_t * ui_Image2;
extern lv_obj_t * ui_TextArea1;
extern lv_obj_t * ui_TextArea2;
extern lv_obj_t * ui_TextArea3;
extern lv_obj_t * ui_Keyboard1;
void ta_event_cb(lv_event_t *e);
extern lv_obj_t * ui____initial_actions0;


LV_IMG_DECLARE(ui_img_pic1_png);    // assets/pic1.png
LV_IMG_DECLARE(ui_img_pic2_png);    // assets/pic2.png
LV_IMG_DECLARE(ui_img_pic3_png);    // assets/pic3.png






void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
