// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button21 = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_Button21, 63);
    lv_obj_set_height(ui_Button21, 68);
    lv_obj_set_x(ui_Button21, -38);
    lv_obj_set_y(ui_Button21, 12);
    lv_obj_set_align(ui_Button21, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button21, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button21, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button41 = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_Button41, 51);
    lv_obj_set_height(ui_Button41, 58);
    lv_obj_set_x(ui_Button41, 117);
    lv_obj_set_y(ui_Button41, 16);
    lv_obj_set_align(ui_Button41, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button41, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button41, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button81 = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_Button81, 61);
    lv_obj_set_height(ui_Button81, 56);
    lv_obj_set_x(ui_Button81, 42);
    lv_obj_set_y(ui_Button81, 100);
    lv_obj_set_align(ui_Button81, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button81, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button81, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button51 = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_Button51, 57);
    lv_obj_set_height(ui_Button51, 62);
    lv_obj_set_x(ui_Button51, -197);
    lv_obj_set_y(ui_Button51, 98);
    lv_obj_set_align(ui_Button51, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button51, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button51, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button11 = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_Button11, 53);
    lv_obj_set_height(ui_Button11, 55);
    lv_obj_set_x(ui_Button11, -119);
    lv_obj_set_y(ui_Button11, 13);
    lv_obj_set_align(ui_Button11, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button11, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button11, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button71 = lv_btn_create(ui_Button11);
    lv_obj_set_width(ui_Button71, 57);
    lv_obj_set_height(ui_Button71, 50);
    lv_obj_set_x(ui_Button71, 78);
    lv_obj_set_y(ui_Button71, 86);
    lv_obj_set_align(ui_Button71, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button71, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button71, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button31 = lv_btn_create(ui_Button11);
    lv_obj_set_width(ui_Button31, 62);
    lv_obj_set_height(ui_Button31, 64);
    lv_obj_set_x(ui_Button31, 159);
    lv_obj_set_y(ui_Button31, -1);
    lv_obj_set_align(ui_Button31, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button31, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button31, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button61 = lv_btn_create(ui_Button11);
    lv_obj_set_width(ui_Button61, 60);
    lv_obj_set_height(ui_Button61, 50);
    lv_obj_set_x(ui_Button61, -1);
    lv_obj_set_y(ui_Button61, 84);
    lv_obj_set_align(ui_Button61, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button61, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button61, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button01 = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_Button01, 66);
    lv_obj_set_height(ui_Button01, 66);
    lv_obj_set_x(ui_Button01, -199);
    lv_obj_set_y(ui_Button01, 10);
    lv_obj_set_align(ui_Button01, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button01, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button01, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button91 = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_Button91, 54);
    lv_obj_set_height(ui_Button91, 50);
    lv_obj_set_x(ui_Button91, 122);
    lv_obj_set_y(ui_Button91, 98);
    lv_obj_set_align(ui_Button91, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button91, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button91, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ButtonX = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_ButtonX, 64);
    lv_obj_set_height(ui_ButtonX, 50);
    lv_obj_set_x(ui_ButtonX, 202);
    lv_obj_set_y(ui_ButtonX, 13);
    lv_obj_set_align(ui_ButtonX, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonX, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonX, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ButtonCF = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_ButtonCF, 57);
    lv_obj_set_height(ui_ButtonCF, 50);
    lv_obj_set_x(ui_ButtonCF, 197);
    lv_obj_set_y(ui_ButtonCF, 98);
    lv_obj_set_align(ui_ButtonCF, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonCF, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonCF, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image1 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Image1, &ui_img_pic1_png);
    lv_obj_set_width(ui_Image1, LV_SIZE_CONTENT);   /// 480
    lv_obj_set_height(ui_Image1, LV_SIZE_CONTENT);    /// 320
    lv_obj_set_align(ui_Image1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TextAreaS1 = lv_textarea_create(ui_Screen1);
    lv_obj_set_width(ui_TextAreaS1, 201);
    lv_obj_set_height(ui_TextAreaS1, 46);
    lv_obj_set_x(ui_TextAreaS1, -1);
    lv_obj_set_y(ui_TextAreaS1, -67);
    lv_obj_set_align(ui_TextAreaS1, LV_ALIGN_CENTER);
    lv_textarea_set_max_length(ui_TextAreaS1, 20);
    lv_textarea_set_text(ui_TextAreaS1, "        ENTER PIN ");
    lv_textarea_set_placeholder_text(ui_TextAreaS1, "Placeholder...");
    lv_obj_set_style_text_color(ui_TextAreaS1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TextAreaS1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TextAreaS1, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_TextAreaS1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_TextAreaS1, lv_color_hex(0x0D1720), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TextAreaS1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);



    lv_obj_add_event_cb(ui_Button21, ui_event_Button21, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button41, ui_event_Button41, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button81, ui_event_Button81, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button51, ui_event_Button51, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button71, ui_event_Button71, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button31, ui_event_Button31, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button61, ui_event_Button61, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button11, ui_event_Button11, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button01, ui_event_Button01, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button91, ui_event_Button91, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonX, ui_event_ButtonX, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonCF, ui_event_ButtonCF, LV_EVENT_ALL, NULL);

}
