// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void ui_Screen2_screen_init(void)
{
    ui_Screen2 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button12 = lv_btn_create(ui_Screen2);
    lv_obj_set_width(ui_Button12, 70);
    lv_obj_set_height(ui_Button12, 62);
    lv_obj_set_x(ui_Button12, -182);
    lv_obj_set_y(ui_Button12, 5);
    lv_obj_set_align(ui_Button12, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button12, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button12, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button22 = lv_btn_create(ui_Screen2);
    lv_obj_set_width(ui_Button22, 72);
    lv_obj_set_height(ui_Button22, 64);
    lv_obj_set_x(ui_Button22, -78);
    lv_obj_set_y(ui_Button22, -3);
    lv_obj_set_align(ui_Button22, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button22, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button22, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button32 = lv_btn_create(ui_Screen2);
    lv_obj_set_width(ui_Button32, 60);
    lv_obj_set_height(ui_Button32, 60);
    lv_obj_set_x(ui_Button32, 77);
    lv_obj_set_y(ui_Button32, -1);
    lv_obj_set_align(ui_Button32, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button32, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button32, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button42 = lv_btn_create(ui_Screen2);
    lv_obj_set_width(ui_Button42, 77);
    lv_obj_set_height(ui_Button42, 71);
    lv_obj_set_x(ui_Button42, 181);
    lv_obj_set_y(ui_Button42, -3);
    lv_obj_set_align(ui_Button42, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button42, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button42, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button52 = lv_btn_create(ui_Screen2);
    lv_obj_set_width(ui_Button52, 71);
    lv_obj_set_height(ui_Button52, 50);
    lv_obj_set_x(ui_Button52, 203);
    lv_obj_set_y(ui_Button52, -127);
    lv_obj_set_align(ui_Button52, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button52, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button52, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image3 = lv_img_create(ui_Screen2);
    lv_img_set_src(ui_Image3, &ui_img_pic2_png);
    lv_obj_set_width(ui_Image3, LV_SIZE_CONTENT);   /// 480
    lv_obj_set_height(ui_Image3, LV_SIZE_CONTENT);    /// 320
    lv_obj_set_align(ui_Image3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_Button12, ui_event_Button12, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button22, ui_event_Button22, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button32, ui_event_Button32, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button42, ui_event_Button42, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button52, ui_event_Button52, LV_EVENT_ALL, NULL);

}
